export const USER_NAME_CHANGE = 'user_name_change'
export const USER_SCORE_CHANGE = 'user_score_change'
export const GAME_STARTED = 'game_started'
export const USER_NAME_SELECTED = 'user_name_selected'
export const LOAD_USER_RECORDS = 'load_user_records'


export const LOAD_QUESTIONS = 'load_questions'
export const ADD_QUESTION_TO_SET = 'add_question_to_set'
export const RESET_GAME = 'reset_game'
export const LOADING_QUESTIONS = 'loading_questions'
export const SELECTED_ANSWER = 'selected_answer'
export const RIGHT_ANSWER = 'right_answer'
export const GO_TO_NEXT_QUESTION = 'go_to_next_question'
export const SET_CURRENT_RIGHT_ANSWER = 'set_current_right_answer'
export const ADD_PLAYER_TO_RANKING = 'add_player_to_ranking'