export const artists = [
    'Bob Marley',
    'Jack Johnson',
    'John Mayer',
    'Ben Harper',
    'Queen',
    'Bon Jovi',
    'Bee Gees',
    'Eagles',
    'Michael Jackson',
    'Foo Fighters',
    'Oasis',
    'Coldplay',
    'Maroon 5',
    'Goo goo dolls',
    'Elvis Presley',
    'Frank Sinatra',
    'Drake',
    'Backstreet Boys',
    'Michael Bublé',
    'Ariana Grande',
    'Paul McCartney',
    'Justin Bieber',
    'Elton John',
    'Beatles',
    'U2',
    'Pink Floyd',
    'Beyoncé',
    'Whitney Houston',
    'Mariah Carey',
    'Prince',
    'David Bowie',
    'Stevie Wonder',
    'James Brown',
    'Ray Charles',
    'Bob Dylan',
    'Johnny Cash',
    'Aerosmith',
    'Christina Aguilera',
    'Bruno Mars',
    'Tina Turner',
    'Amy Winehouse',
    'Alicia Keys',
    'Lady Gaga',
    'James Morrison'
]
export const apiKey = '739d3751172543d0cb9b306049d4cbe2'
export const questionsTypes = [
    'read-track-guess-artist',
    'read-artist-guess-track',
    'read-lyrics-guess-artist',
]
export const numberOfQuestions = 10
export const numberOfWrongAnswers = 3